// Generates src/generated/versions.ts from package-lock.json @github/copilot version.
// Run automatically via prebuild hook.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageLock = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "package-lock.json"), "utf-8"));
const cliVersion = packageLock.packages["node_modules/@github/copilot"].version;

const code = `// Generated by scripts/generate-versions.ts - DO NOT EDIT
export const PREFERRED_CLI_VERSION = "${cliVersion}";
`;

fs.mkdirSync(path.join(__dirname, "..", "src", "generated"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "..", "src", "generated", "versions.ts"), code);
console.log(`Generated src/generated/versions.ts with PREFERRED_CLI_VERSION="${cliVersion}"`);
